spring:
  application:
    name: user-service

  config:
    import: configserver:http://localhost:8888

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/airline_location_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Deva#62010}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:5001}

jwt:
  algorithm:
    key: ${JWT_SECRET:}
  issuer:
    name: ${JWT_ISSUER:Devanand Pandey}
  expiry:
    duration: ${JWT_EXPIRY_MS:86400000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}